name: Windows GitHub CI

on:
  pull_request: []
  push: []
  schedule:
    # Run this experiment every 4th hour
    # * is a special character in YAML so you have to quote this string
    - cron:  '* */8 * * *'

jobs:
  build-and-test-extra:
    strategy:
      matrix:
        platform:
          - msvc-arch: x64
            cmake-arch: x64
            openssl-target: VC-WIN64A
          - msvc-arch: x86
            cmake-arch: Win32
            openssl-target: VC-WIN32
    runs-on: windows-latest
    steps:
      - name: install MSVC for ${{ matrix.platform.msvc-arch }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.platform.msvc-arch }}
      - name: install cpanm and Test2::V0
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: Test2::V0
      - name: checkout Extra
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: checkout OpenSSL
        uses: actions/checkout@v2
        with:
          repository: openssl/openssl
          path: openssl
      - name: configure OpenSSL for ${{matrix.platform.openssl-target}}
        run: |
          $cwd = Get-Location
          mkdir ..\openssl-install
          perl Configure ${{matrix.platform.openssl-target}} --prefix="$cwd\..\openssl-install" no-asm no-shared
        working-directory: openssl
      - name: build+install OpenSSL
        run: nmake /S install_sw
        working-directory: openssl
      - name: configure the Extra provider for ${{ matrix.platform.cmake-arch }}
        run: |
          $cwd = Get-Location
          cmake -A ${{ matrix.platform.cmake-arch }} -DCMAKE_PREFIX_PATH="$cwd\openssl-install" -S . -B _build
      - name: build the Extra provider
        run: cmake --build _build
      - name: test the Extra provider
        run: ctest -VV -C Debug
        working-directory: _build
