name: Windows GitHub CI

on: [pull_request, push]

jobs:
  build-and-test-extra:
    strategy:
      matrix:
        platform:
          - arch: x64
            target: VC-WIN64A
          - arch: x86
            target: VC-WIN32
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.platform.arch }}
      - name: checkout Extra
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: checkout OpenSSL
        uses: actions/checkout@v2
        with:
          repository: openssl/openssl
          path: openssl
      - name: configure OpenSSL for ${{matrix.platform.target}}
        run: |
          $cwd = Get-Location
          mkdir ..\openssl-install
          perl Configure ${{matrix.platform.target}} --prefix="$cwd\..\openssl-install" no-asm
        working-directory: openssl
      - name: build+install OpenSSL
        run: nmake /S install_sw
        working-directory: openssl
      - name: configure the Extra provider for ${{ matrix.platform.arch }}
        run: |
          $cwd = Get-Location
          cmake -A  ${{ matrix.platform.arch }} -DCMAKE_PREFIX_PATH="$cwd\openssl-install" -S . -B _build
      - name: build the Extra provider
        run: cmake --build _build
