name: GitHub CI

on: [pull_request, push]

jobs:
  build-and-test-extra:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout Extra
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: checkout OpenSSL
        uses: actions/checkout@v3
        with:
          repository: openssl/openssl
          path: openssl
      - name: configure OpenSSL with compiler ${{matrix.compiler}}
        run: |
          mkdir ../openssl-install
          ./Configure --prefix=$(cd ..; pwd)/openssl-install --libdir=lib
        working-directory: openssl
      - name: build+install OpenSSL
        run: make -s install_sw
        working-directory: openssl
      - name: configure the Extra provider with compiler ${{matrix.compiler}}
        run: cmake -DCMAKE_PREFIX_PATH="$(pwd)/openssl-install"
                   -S . -B _build
      - name: build the Extra provider
        run: cmake --build _build
