name: "Linux & MacOS GitHub CI"

on:
  pull_request: []
  push: []
  schedule:
    # Run this experiment every 4th hour
    # * is a special character in YAML so you have to quote this string
    - cron:  '* */8 * * *'

jobs:
  build-and-test-extra:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - name: install cpanm and Test2::V0
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: Test2::V0
      - name: install libcrypt-dev (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libcrypt-dev
          version: 1.0
      - name: checkout Extra
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: checkout OpenSSL
        uses: actions/checkout@v3
        with:
          repository: openssl/openssl
          path: openssl
      - name: configure OpenSSL with compiler ${{matrix.compiler}}
        run: |
          mkdir ../openssl-install
          ./Configure --prefix=$(cd ..; pwd)/openssl-install --libdir=lib
        working-directory: openssl
      - name: build+install OpenSSL
        run: make -s install_sw
        working-directory: openssl
      - name: configure the Extra provider with compiler ${{matrix.compiler}}
        run: cmake -DCMAKE_PREFIX_PATH="$(pwd)/openssl-install"
                   -S . -B _build
      - name: build the Extra provider
        run: cmake --build _build
      - name: test the Extra provider
        run: ctest -VV
        working-directory: _build
